"""Case file exports: JSON, CSV and PDF.

Every export carries the provenance of the information and restates that a score
is not evidence. Exporting is an action recorded in the audit log.
"""
from __future__ import annotations

import csv
import io
import json
import uuid
from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.evidence import Contradiction, Finding, Relationship, Source, TimelineEvent
from app.models.identity import Identifier, Platform, SocialProfile, Username
from app.models.investigation import Investigation, Note, Person
from app.models.ops import PluginRun, Search
from app.services.correlation import recompute_person_score

DISCLAIMER = (
    "Document generated by ReconCore OSINT from public sources. Scores are "
    "indicative and explainable; they are neither proof of identity nor a legal "
    "conclusion. Every piece of information must be verified before use."
)


def build_case_file(db: Session, person: Person) -> dict:
    """Assemble the complete representation of a person case file."""
    investigation = db.get(Investigation, person.investigation_id)
    platforms = {p.id: p for p in db.execute(select(Platform)).scalars().all()}

    identifiers = db.execute(
        select(Identifier).where(Identifier.person_id == person.id)
    ).scalars().all()
    usernames = db.execute(
        select(Username).where(Username.person_id == person.id)
    ).scalars().all()
    profiles = db.execute(
        select(SocialProfile).where(SocialProfile.person_id == person.id)
    ).scalars().all()
    findings = db.execute(
        select(Finding).where(Finding.person_id == person.id)
    ).scalars().all()
    sources = db.execute(
        select(Source).where(Source.investigation_id == person.investigation_id)
    ).scalars().all()
    relationships = db.execute(
        select(Relationship).where(Relationship.investigation_id == person.investigation_id)
    ).scalars().all()
    timeline = db.execute(
        select(TimelineEvent)
        .where(TimelineEvent.person_id == person.id)
        .order_by(TimelineEvent.at.desc())
    ).scalars().all()
    contradictions = db.execute(
        select(Contradiction).where(Contradiction.person_id == person.id)
    ).scalars().all()
    searches = db.execute(
        select(Search).where(Search.person_id == person.id).order_by(Search.created_at.desc())
    ).scalars().all()
    runs = db.execute(
        select(PluginRun).where(PluginRun.person_id == person.id)
    ).scalars().all()
    notes = db.execute(
        select(Note).where(Note.person_id == person.id)
    ).scalars().all()

    score = recompute_person_score(db, person)

    return {
        "generated_at": datetime.now(UTC).isoformat(),
        "disclaimer": DISCLAIMER,
        "investigation": {
            "id": str(investigation.id) if investigation else None,
            "title": investigation.title if investigation else None,
            "entity_type": investigation.entity_type if investigation else None,
            "legal_basis": investigation.legal_basis if investigation else None,
        },
        "person": {
            "id": str(person.id),
            "display_name": person.display_name,
            "first_name": person.first_name,
            "last_name": person.last_name,
            "full_name": person.full_name,
            "date_of_birth": person.date_of_birth.isoformat() if person.date_of_birth else None,
            "profession": person.profession,
            "summary": person.summary,
            "tags": [t.name for t in person.tags],
            "score": score.as_dict(),
        },
        "identifiers": [
            {
                "type": i.type,
                "value": i.value,
                "normalized_value": i.normalized_value,
                "platform": platforms[i.platform_id].name if i.platform_id in platforms else None,
                "status": i.status,
                "confidence": i.confidence,
                "is_former": i.is_former,
                "source_id": str(i.source_id) if i.source_id else None,
                "note": i.note,
            }
            for i in identifiers
        ],
        "usernames": [
            {
                "value": u.value,
                "platform": platforms[u.platform_id].name if u.platform_id in platforms else None,
                "url": u.url,
                "status": u.status,
                "confidence": u.confidence,
                "is_variant": u.is_variant,
                "variant_rule": u.variant_rule,
                "discovered_at": u.discovered_at.isoformat() if u.discovered_at else None,
                "note": u.note,
            }
            for u in usernames
        ],
        "social_profiles": [
            {
                "platform": platforms[p.platform_id].name if p.platform_id in platforms else None,
                "username": p.username,
                "url": p.url,
                "status": p.status,
                "confidence": p.confidence,
                "display_name": p.display_name,
                "bio": p.bio,
                "followers": p.followers,
                "following": p.following,
                "posts_count": p.posts_count,
                "is_verified": p.is_verified,
                "is_private": p.is_private,
                "discovered_by": p.discovered_by_plugin,
            }
            for p in profiles
        ],
        "findings": [
            {
                "type": f.type,
                "title": f.title,
                "status": f.status,
                "confidence": f.confidence,
                "plugin": f.plugin,
                "discovered_at": f.discovered_at.isoformat() if f.discovered_at else None,
                "source_id": str(f.source_id) if f.source_id else None,
                "content": f.content,
                "score_explanation": f.score_explanation,
            }
            for f in findings
        ],
        "sources": [
            {
                "id": str(s.id),
                "kind": s.kind,
                "url": s.url,
                "title": s.title,
                "description": s.description,
                "plugin": s.plugin,
                "reliability": s.reliability,
                "date_discovered": s.date_discovered.isoformat() if s.date_discovered else None,
                "date_checked": s.date_checked.isoformat() if s.date_checked else None,
            }
            for s in sources
        ],
        "relationships": [
            {
                "source": f"{r.source_type}:{r.source_ref}",
                "target": f"{r.target_type}:{r.target_ref}",
                "type": r.type,
                "confidence": r.confidence,
                "status": r.status,
            }
            for r in relationships
        ],
        "contradictions": [
            {
                "field": c.field,
                "value_a": c.value_a,
                "value_b": c.value_b,
                "resolved": c.resolved,
                "resolution": c.resolution,
            }
            for c in contradictions
        ],
        "timeline": [
            {
                "at": e.at.isoformat(),
                "kind": e.kind,
                "message": e.message,
                "actor": e.actor,
            }
            for e in timeline
        ],
        "search_history": [
            {
                "target_type": s.target_type,
                "target_value": s.target_value,
                "depth": s.depth,
                "status": s.status,
                "started_at": s.started_at.isoformat() if s.started_at else None,
                "finished_at": s.finished_at.isoformat() if s.finished_at else None,
                "stats": s.stats,
            }
            for s in searches
        ],
        "plugin_runs": [
            {
                "plugin": r.plugin,
                "target": f"{r.target_type}={r.target_value}",
                "status": r.status,
                "items_found": r.items_found,
                "duration_ms": r.duration_ms,
                "error": r.error,
            }
            for r in runs
        ],
        "notes": [{"title": n.title, "body": n.body} for n in notes],
    }


def to_json(case_file: dict) -> bytes:
    return json.dumps(case_file, ensure_ascii=False, indent=2).encode("utf-8")


def to_csv(case_file: dict) -> bytes:
    """Flat CSV: one row per item, across every section."""
    buffer = io.StringIO()
    writer = csv.writer(buffer, delimiter=";", quoting=csv.QUOTE_MINIMAL)
    writer.writerow(["section", "type", "value", "platform", "status", "confidence", "source", "note"])

    for identifier in case_file["identifiers"]:
        writer.writerow([
            "identifier", identifier["type"], identifier["value"],
            identifier["platform"] or "", identifier["status"],
            identifier["confidence"], identifier["source_id"] or "", identifier["note"] or "",
        ])
    for username in case_file["usernames"]:
        writer.writerow([
            "username", "variant" if username["is_variant"] else "username",
            username["value"], username["platform"] or "", username["status"],
            username["confidence"], username["url"] or "", username["note"] or "",
        ])
    for profile in case_file["social_profiles"]:
        writer.writerow([
            "social_profile", profile["platform"] or "", profile["username"],
            profile["platform"] or "", profile["status"], profile["confidence"],
            profile["url"] or "", profile["display_name"] or "",
        ])
    for finding in case_file["findings"]:
        writer.writerow([
            "finding", finding["type"], finding["title"], finding["plugin"] or "",
            finding["status"], finding["confidence"], finding["source_id"] or "", "",
        ])
    for source in case_file["sources"]:
        writer.writerow([
            "source", source["kind"], source["title"] or "", source["plugin"] or "",
            "", source["reliability"], source["url"] or "", source["description"] or "",
        ])
    for contradiction in case_file["contradictions"]:
        writer.writerow([
            "contradiction", contradiction["field"], contradiction["value_a"], "",
            "resolved" if contradiction["resolved"] else "open", "",
            contradiction["value_b"], contradiction["resolution"] or "",
        ])
    return buffer.getvalue().encode("utf-8-sig")


def to_pdf(case_file: dict) -> bytes:
    """Complete PDF report (reportlab, no system dependency)."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
        title=f"Case file - {case_file['person']['display_name']}",
    )
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("Small", parent=styles["Normal"], fontSize=7.5, leading=9.5))
    styles.add(ParagraphStyle("Warn", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#8a4b00"), alignment=TA_LEFT))

    story = []
    person = case_file["person"]
    story.append(Paragraph(f"Case file - {person['display_name']}", styles["Title"]))
    story.append(Paragraph(f"Generated on {case_file['generated_at']}", styles["Small"]))
    story.append(Spacer(1, 6))
    story.append(Paragraph(DISCLAIMER, styles["Warn"]))
    story.append(Spacer(1, 10))

    score = person["score"]
    story.append(Paragraph("Consolidation score", styles["Heading2"]))
    story.append(Paragraph(f"{score['score']} / 100 - {score['verdict']}", styles["Normal"]))
    story.append(
        _table(
            [["Criterion", "Points", "Detail"]]
            + [[c["label"], str(c["points"]), c["detail"] or ""] for c in score["breakdown"]],
            styles,
            widths=[70 * mm, 20 * mm, 84 * mm],
        )
    )

    sections = [
        ("Identifiers", ["Type", "Value", "Status", "Conf."],
         [[i["type"], i["value"], i["status"], f"{i['confidence']:.2f}"] for i in case_file["identifiers"]],
         [30 * mm, 80 * mm, 34 * mm, 20 * mm]),
        ("Usernames", ["Username", "Platform", "Status", "Hypothesis"],
         [[u["value"], u["platform"] or "-", u["status"], "yes" if u["is_variant"] else "no"] for u in case_file["usernames"]],
         [50 * mm, 45 * mm, 40 * mm, 25 * mm]),
        ("Social profiles", ["Platform", "Username", "URL", "Status"],
         [[p["platform"] or "-", p["username"], p["url"] or "", p["status"]] for p in case_file["social_profiles"]],
         [30 * mm, 35 * mm, 75 * mm, 25 * mm]),
        ("Findings", ["Type", "Title", "Status", "Conf."],
         [[f["type"], f["title"][:90], f["status"], f"{f['confidence']:.2f}"] for f in case_file["findings"]],
         [30 * mm, 90 * mm, 30 * mm, 18 * mm]),
        ("Sources", ["Type", "Title", "URL", "Rel."],
         [[s["kind"], (s["title"] or "")[:50], (s["url"] or "")[:70], f"{s['reliability']:.2f}"] for s in case_file["sources"]],
         [28 * mm, 45 * mm, 82 * mm, 18 * mm]),
        ("Contradictions", ["Field", "Value A", "Value B", "State"],
         [[c["field"], c["value_a"], c["value_b"], "resolved" if c["resolved"] else "OPEN"] for c in case_file["contradictions"]],
         [30 * mm, 55 * mm, 55 * mm, 25 * mm]),
        ("Relationships", ["Source", "Relation", "Target", "Conf."],
         [[r["source"], r["type"], r["target"], f"{r['confidence']:.2f}"] for r in case_file["relationships"]],
         [55 * mm, 35 * mm, 55 * mm, 18 * mm]),
        ("Timeline", ["Date", "Type", "Event"],
         [[e["at"][:19], e["kind"], e["message"][:80]] for e in case_file["timeline"]],
         [35 * mm, 30 * mm, 100 * mm]),
        ("Search history", ["Target", "Depth", "Status", "Results"],
         [[f"{s['target_type']}={s['target_value']}", str(s["depth"]), s["status"],
           str((s["stats"] or {}).get("items", ""))] for s in case_file["search_history"]],
         [75 * mm, 25 * mm, 35 * mm, 30 * mm]),
    ]

    for title, header, rows, widths in sections:
        story.append(PageBreak())
        story.append(Paragraph(f"{title} ({len(rows)})", styles["Heading2"]))
        if rows:
            story.append(_table([header] + rows, styles, widths=widths))
        else:
            story.append(Paragraph("No items.", styles["Small"]))

    doc.build(story)
    return buffer.getvalue()


def _table(data, styles, widths):
    from reportlab.lib import colors
    from reportlab.platypus import Paragraph, Table, TableStyle

    wrapped = [
        [Paragraph(str(cell), styles["Small"]) for cell in row] for row in data
    ]
    table = Table(wrapped, colWidths=widths, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#9ca3af")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f3f4f6")]),
            ]
        )
    )
    return table


def export_filename(person: Person, extension: str) -> str:
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in person.display_name)
    stamp = datetime.now(UTC).strftime("%Y%m%d-%H%M")
    return f"case_{safe}_{stamp}.{extension}"


def person_by_id(db: Session, person_id: uuid.UUID) -> Person | None:
    return db.get(Person, person_id)
